"""
Atmosense Alert Schemas
Typed contracts for alerts and notifications.
"""
from datetime import datetime
from typing import Optional
from pydantic import BaseModel, Field
from backend.core.enums import HazardType, AlertSeverity, RiskLevel, DataMode


class AlertTarget(BaseModel):
    """Target of an alert — an administrative area or location."""
    region_name: str
    region_type: str = Field(..., description="'district', 'state', 'locality', 'custom'")
    latitude: float
    longitude: float
    geometry_geojson: Optional[dict] = None


class Alert(BaseModel):
    """An actionable alert generated by Atmosense."""
    alert_id: str
    hazard_type: HazardType
    severity: AlertSeverity
    affected_region: AlertTarget
    probability: float = Field(..., ge=0.0, le=1.0)
    confidence: float = Field(..., ge=0.0, le=1.0)
    lead_time_hours: float
    forecast_window: str = Field(
        ..., description="e.g. '+2H to +4H'"
    )
    triggering_factors: list[str] = Field(
        default_factory=list,
        description="List of atmospheric factors triggering this alert"
    )
    recommended_action: str = Field(
        ..., description="Recommended disaster-management action"
    )
    timestamp: datetime
    valid_from: datetime
    valid_until: datetime
    model_version: str
    data_mode: DataMode
    is_simulated: bool = Field(
        True,
        description="True if this is a simulated/demo alert, not an actual operational alert"
    )


class AlertResponse(BaseModel):
    """API response for alerts."""
    status: str = "ok"
    data_mode: DataMode
    generated_at: datetime
    active_alerts: list[Alert]
    total_count: int = 0
    disclaimer: str = Field(
        default="PROTOTYPE: These are simulated alerts for demonstration purposes. "
        "They are NOT official meteorological warnings.",
        description="Legal/operational disclaimer"
    )


class NotificationChannel(BaseModel):
    """Configuration for a notification delivery channel."""
    channel_type: str = Field(..., description="'dashboard', 'sms', 'whatsapp', 'email'")
    enabled: bool = True
    is_simulated: bool = True
    description: str = ""
